#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server.
if [ $# -lt 3]
then 
	echo "Bash script that transfers a file from our client to a server"
else
	scp -o StrictHostKeyChecking -i $4 $1 "$3@$2:/home/$3"
fi
